### ISSUE TITLE
Not possible to install

### ISSUE THREAD

**Issue by fsolar** [IjzerenHein/react-firestore-mobx#1]
Im getting this error after "yarn add firestore-react-mobx":

`
yarn add v1.1.0
[1/4] Resolving packages...
error Couldn't find package "firestore-react-mobx" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
`

same with npm

**Comment by IjzerenHein** [comment]
Hi, cool for trying out my new package! I just started it and hadn't published to npm yet. Just published it, should work now. 🖖

**Comment by IjzerenHein** [comment]
Hey, I've made some changes to the API to make it easier to use. Also, I've added API documentation with examples to help anyone get started.

Let me know whether I can close this issue.

cheers, Hein

**Comment by fsolar** [comment]
Hi, I'm trying the example now. I'll tell you later, thanks!

**Comment by IjzerenHein** [comment]
Cool, let me know if you have issues.

**Comment by fsolar** [comment]
Hi, im working with this repo [https://github.com/rwieruch/react-mobx-firebase-authentication](url) wish already include react router v4, mobx and firebase authentication, so is a good starting point. But i cant make it work with your repo... 😞

**Comment by IjzerenHein** [comment]
If you can tell me what's not working, I can maybe help you. Do you have a public repo I can take a look at?

**Comment by fsolar** [comment]
Yes [https://github.com/fsolar/cjm33_2](url). create-react-app bootrasped. 
Key info in the Readme.md. Thanks a lot!!!!

**Comment by IjzerenHein** [comment]
My god, your code is a mess..

Anyway, I think this is the reason of the error:

IngresoDeVehiculos.js
```js
  ...
          <Col s={12}>
            {this.renderCars}
          </Col>
   ...
```

You forgot to actually call the renderCars function. It should be `{this.renderCars()}`

**Comment by fsolar** [comment]
Hahaha yes I know... I'm a web designer and I'm new to the React world and JS ecosystem, but thanks again, that worked, it was just a typo.

**Comment by IjzerenHein** [comment]
Your welcome 👍
